name: Integration Test
on: [pull_request]
jobs:
 
  dusk-php:
    runs-on: ubuntu-latest
    env:
      APP_URL: "http://127.0.0.1:8000"
      DB_USERNAME: root
      DB_PASSWORD: root
      MAIL_MAILER: log
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Choose your preferred Node.js version
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: imagick, swoole    
      - name: Prepare The Environment
        run: |
          cd magic-portfolio
          cp .env.example .env
    #   - name: Create Database
    #     run: |
    #       sudo systemctl start mysql
    #       mysql --user="root" --password="root" -e "CREATE DATABASE \`harizcor_bhirawatour_test\` character set UTF8mb4 collate utf8mb4_bin;"
      - name: Install Composer Dependencies
        run: |
          cd magic-portfolio
          composer update
          composer install --no-progress --prefer-dist --optimize-autoloader
          php -v
      - name: Install npm Packages
        run: |
          cd magic-portfolio
          npm ci
      - name: Generate Application Key
        run: |
          cd magic-portfolio
          php artisan key:generate
      - name: Upgrade Chrome Driver
        run: |
          cd magic-portfolio
          php artisan dusk:chrome-driver --detect
      - name: Start Chrome Driver
        run: |
          cd magic-portfolio
          ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
      - name: Run Laravel Server
        run: |
          cd magic-portfolio
          php artisan serve --no-reload &
      - name: Run npm
        run: |
          cd magic-portfolio
          LARAVEL_BYPASS_ENV_CHECK=1 npm run dev &
      - name: Run Dusk Tests
        run: |
          cd magic-portfolio
          php artisan dusk
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tests/Browser/screenshots
      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: console
          path: tests/Browser/console